import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jnv19
 */
public class ADDSTOCK1 extends javax.swing.JFrame {

    /**
     * Creates new form ADDSTOCK1
     */
    public ADDSTOCK1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        chilli = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        ground = new javax.swing.JTextField();
        jeera = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        phutana = new javax.swing.JTextField();
        dalchini = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        oil = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        sugar = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        dal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        atta = new javax.swing.JTextField();
        tea = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        salt = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        besan = new javax.swing.JTextField();
        idly = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        maida = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jaggery = new javax.swing.JTextField();
        dalda = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        match = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        meal = new javax.swing.JTextField();
        bisc = new javax.swing.JTextField();
        eggs = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        papad = new javax.swing.JTextField();
        potato = new javax.swing.JTextField();
        boost = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        lpg = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        haldi = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel71.setText("HALDI POWDER");

        chilli.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        chilli.setText("0");

        jLabel72.setText("CHILLI POWDER");

        ground.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ground.setText("0");

        jeera.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jeera.setText("0");

        jLabel74.setText("JEERA");

        phutana.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        phutana.setText("0");

        dalchini.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        dalchini.setText("0");

        jLabel76.setText("DALCHINI");

        jLabel77.setText("IDLY  RAWA");

        jLabel78.setText("DALDA");

        jLabel79.setText("BISCUITS");

        jLabel80.setText("EGGS");

        jLabel81.setText("POTATO");

        jLabel82.setText("PHUTANA");

        jLabel83.setText("GROUNDNUTS");

        jLabel1.setFont(new java.awt.Font("Symbola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 90, 12));
        jLabel1.setText("ADD STOCK ");

        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("RICE");

        rice.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        rice.setText("0");

        jLabel3.setText("DAL");

        jLabel54.setText("OIL");

        oil.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        oil.setText("0");

        jLabel55.setText("SUGAR");

        sugar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        sugar.setText("0");

        jLabel56.setText("TEA");

        dal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        dal.setText("0");

        jLabel4.setText("ATTA");

        atta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        atta.setText("0");

        tea.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tea.setText("0");

        jLabel57.setText("SALT");

        salt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        salt.setText("0");

        jLabel58.setText("BESAN");

        besan.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        besan.setText("0");

        idly.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        idly.setText("0");

        jLabel60.setText("MAIDA");

        maida.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        maida.setText("0");

        jLabel61.setText("JAGGERY");

        jaggery.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jaggery.setText("0");

        dalda.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        dalda.setText("0");

        jLabel63.setText("MATCHBOX");

        match.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        match.setText("0");

        jLabel64.setText("MEAL-MAKER");

        meal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        meal.setText("0");

        bisc.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        bisc.setText("0");

        eggs.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        eggs.setText("0");

        jLabel67.setText("PAPAD");

        papad.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        papad.setText("0");

        potato.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        potato.setText("0");

        boost.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        boost.setText("0");

        jLabel69.setText("BOOST");

        lpg.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lpg.setText("0");

        jLabel70.setText("L.P.G.");

        haldi.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        haldi.setText("0");

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("AMOUNT (KG)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitbtn)
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phutana, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel5)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(132, 132, 132)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(atta, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(besan, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idly, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maida, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jaggery, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dalda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(match, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bisc, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eggs, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(papad, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(potato, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(boost, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(haldi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chilli, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jeera, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dalchini, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(backbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(137, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1391, Short.MAX_VALUE)
                .addComponent(phutana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(submitbtn)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(atta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel54)
                        .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel56)
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel57)
                        .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel58)
                        .addComponent(besan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(maida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel61)
                        .addComponent(jaggery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dalda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel78))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel63)
                        .addComponent(match, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel64)
                        .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel79))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eggs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel80))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel67)
                        .addComponent(papad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(potato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel69)
                        .addComponent(boost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel70)
                        .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel71)
                        .addComponent(haldi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel72)
                        .addComponent(chilli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel83))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel74)
                        .addComponent(jeera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addComponent(jLabel82)
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel76)
                        .addComponent(dalchini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                    .addComponent(backbtn)
                    .addContainerGap()))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed

        try{

            Class.forName("java.sql.DriverManager");
            Connection dibas=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mess","root","password");
            Statement kush= dibas.createStatement();
            int Rice=0,Dal=0,Atta=0,Oil=0,Sugar=0,Tea=0,Salt=0,Besan=0,Idlyrawa=0,Maida=0,Jaggery=0,Dalda=0,Matchbox=0,Mealmaker=0,
            Biscuits=0,Eggs=0,Papad=0,Potatoes=0,Boost=0,Lpg=0,Haldipowder=0,
            Chillipowder=0,Groundnuts=0,Jeera=0,Phutan=0,Dalchini =0;

            //  String query1="update stock set rice=rice+"+Rice+";";
            // alpesh.executeUpdate(query1);
            
             Rice=Integer.parseInt(rice.getText());
        Dal=Integer.parseInt(dal.getText());
        Atta=Integer.parseInt(atta.getText());
        Oil=Integer.parseInt(oil.getText());
        Sugar=Integer.parseInt(sugar.getText());
        Tea=Integer.parseInt(tea.getText());
        Salt=Integer.parseInt(salt.getText());
        Besan=Integer.parseInt(besan.getText());
        Maida=Integer.parseInt(maida.getText());
        Jaggery=Integer.parseInt(jaggery.getText());
        Dalda=Integer.parseInt(dalda.getText());
        Matchbox=Integer.parseInt(match.getText());
        Idlyrawa=Integer.parseInt(idly.getText());
        Mealmaker=Integer.parseInt(meal.getText());
        Biscuits=Integer.parseInt(bisc.getText());
        Eggs=Integer.parseInt(eggs.getText());
        Papad=Integer.parseInt(papad.getText());
        Potatoes=Integer.parseInt(potato.getText());
        Boost=Integer.parseInt(boost.getText());
        Lpg=Integer.parseInt(lpg.getText());
        Haldipowder=Integer.parseInt(haldi.getText());
        Chillipowder=Integer.parseInt(chilli.getText());
        Groundnuts=Integer.parseInt(ground.getText());
        Jeera=Integer.parseInt(jeera.getText());
        Phutan=Integer.parseInt(phutana.getText());
        Dalchini=Integer.parseInt(dalchini.getText());

            String query1="update stock set rice=rice+"+Rice+";";
            kush.executeUpdate(query1);

            String query2="update stock set dal=dal+"+Dal+";";
            kush.executeUpdate(query2);

            String query3="update stock set atta=atta+"+Atta+";";
            kush.executeUpdate(query3);

            String query4="update stock set oil=oil+"+Oil+";";
            kush.executeUpdate(query4);

            String query5="update stock set sugar=sugar+"+Sugar+";";
            kush.executeUpdate(query5);

            String query6="update stock set tea=tea+"+Tea+";";
            kush.executeUpdate(query6);

            String query7="update stock set salt=salt+"+Salt+";";
            kush.executeUpdate(query7);

            String query8="update stock set besan=besan+"+Besan+";";
            kush.executeUpdate(query8);

            String query9="update stock set idlyrawa=idlyrawa+"+Idlyrawa+";";
            kush.executeUpdate(query9);

            String query10="update stock set maida=maida+"+Maida+";";
            kush.executeUpdate(query10);

            String query11="update stock set jaggery=jaggery+"+Jaggery+";";
            kush.executeUpdate(query11);

            String query12="update stock set dalda=dalda+"+Dalda+";";
            kush.executeUpdate(query12);

            String query13="update stock set matchbox=matchbox+"+Matchbox+";";
            kush.executeUpdate(query13);

            String query14="update stock set mealmaker=mealmaker+"+Mealmaker+";";
            kush.executeUpdate(query14);

            String query15="update stock set biscuits=biscuits+"+Biscuits+";";
            kush.executeUpdate(query15);

            String query16="update stock set eggs=eggs+"+Eggs+";";
            kush.executeUpdate(query16);

            String query17="update stock set papad=papad+"+Papad+";";
            kush.executeUpdate(query17);

            String query18="update stock set potatoes=potatoes+"+Potatoes+";";
            kush.executeUpdate(query18);

            String query19="update stock set boost=boost+"+Boost+";";
            kush.executeUpdate(query19);

            String query20="update stock set lpg=lpg+"+Lpg+";";
            kush.executeUpdate(query20);

            String query21="update stock set haldipowder=haldipowder+"+Haldipowder+";";
            kush.executeUpdate(query21);

            String query22="update stock set chillipowder=chillipowder+"+Chillipowder+";";
            kush.executeUpdate(query22);

            String query23="update stock set groundnuts=groundnuts+"+Groundnuts+";";
            kush.executeUpdate(query23);

            String query24="update stock set jeera=jeera+"+Jeera+";";
            kush.executeUpdate(query24);

            String query25="update stock set phutan=phutan+"+Phutan+";";
            kush.executeUpdate(query25);

            String query26="update stock set dalchini=dalchini+"+Dalchini+";";
            kush.executeUpdate(query26);
            JOptionPane.showMessageDialog(this,"YOU HAVE SUBMITTED SUCCESSFULLY"+"\n"+"THANK YOU");

            submitbtn.setEnabled(false); }                                         
catch(Exception e)       
{
     JOptionPane.showMessageDialog(this, e.getMessage());
}

    }//GEN-LAST:event_submitbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.show(false);
        new STOCK1().show();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDSTOCK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDSTOCK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDSTOCK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDSTOCK1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDSTOCK1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atta;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField besan;
    private javax.swing.JTextField bisc;
    private javax.swing.JTextField boost;
    private javax.swing.JTextField chilli;
    private javax.swing.JTextField dal;
    private javax.swing.JTextField dalchini;
    private javax.swing.JTextField dalda;
    private javax.swing.JTextField eggs;
    private javax.swing.JTextField ground;
    private javax.swing.JTextField haldi;
    private javax.swing.JTextField idly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaggery;
    private javax.swing.JTextField jeera;
    private javax.swing.JTextField lpg;
    private javax.swing.JTextField maida;
    private javax.swing.JTextField match;
    private javax.swing.JTextField meal;
    private javax.swing.JTextField oil;
    private javax.swing.JTextField papad;
    private javax.swing.JTextField phutana;
    private javax.swing.JTextField potato;
    private javax.swing.JTextField rice;
    private javax.swing.JTextField salt;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField sugar;
    private javax.swing.JTextField tea;
    // End of variables declaration//GEN-END:variables
}
