
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jnv19
 */
public class BILLING extends javax.swing.JFrame {

    /**
     * Creates new form stock_rate
     */
    public BILLING() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        chilli = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        ground = new javax.swing.JTextField();
        jeera = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        phutana = new javax.swing.JTextField();
        dalchini = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        oil = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        sugar = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        dal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        atta = new javax.swing.JTextField();
        tea = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        salt = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        besan = new javax.swing.JTextField();
        idly = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        maida = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jaggery = new javax.swing.JTextField();
        dalda = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        match = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        meal = new javax.swing.JTextField();
        bisc = new javax.swing.JTextField();
        eggs = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        papad = new javax.swing.JTextField();
        potato = new javax.swing.JTextField();
        boost = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        lpg = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        haldi = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        monthlybill = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bill = new javax.swing.JTextField();
        calc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel71.setText("HALDI POWDER");

        chilli.setEditable(false);
        chilli.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel72.setText("CHILLI POWDER");

        ground.setEditable(false);
        ground.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jeera.setEditable(false);
        jeera.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel74.setText("JEERA");

        phutana.setEditable(false);
        phutana.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        dalchini.setEditable(false);
        dalchini.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel76.setText("DALCHINI");

        jLabel77.setText("IDLY  RAWA");

        jLabel78.setText("DALDA");

        jLabel79.setText("BISCUITS");

        jLabel80.setText("EGGS");

        jLabel81.setText("POTATO");

        jLabel82.setText("PHUTANA");

        jLabel83.setText("GROUNDNUTS");

        jLabel1.setFont(new java.awt.Font("Typesource Extol S BRK", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 20, 237));
        jLabel1.setText("BILL");

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("RICE");

        rice.setEditable(false);
        rice.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel3.setText("DAL");

        jLabel54.setText("OIL");

        oil.setEditable(false);
        oil.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel55.setText("SUGAR");

        sugar.setEditable(false);
        sugar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel56.setText("TEA");

        dal.setEditable(false);
        dal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel4.setText("ATTA");

        atta.setEditable(false);
        atta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        tea.setEditable(false);
        tea.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel57.setText("SALT");

        salt.setEditable(false);
        salt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel58.setText("BESAN");

        besan.setEditable(false);
        besan.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        idly.setEditable(false);
        idly.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel60.setText("MAIDA");

        maida.setEditable(false);
        maida.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel61.setText("JAGGERY");

        jaggery.setEditable(false);
        jaggery.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        dalda.setEditable(false);
        dalda.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel63.setText("MATCHBOX");

        match.setEditable(false);
        match.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel64.setText("MEAL-MAKER");

        meal.setEditable(false);
        meal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        bisc.setEditable(false);
        bisc.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        eggs.setEditable(false);
        eggs.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel67.setText("PAPAD");

        papad.setEditable(false);
        papad.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        potato.setEditable(false);
        potato.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        boost.setEditable(false);
        boost.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel69.setText("BOOST");

        lpg.setEditable(false);
        lpg.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel70.setText("L.P.G.");

        haldi.setEditable(false);
        haldi.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1)
                .addGap(403, 672, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dalchini, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jeera, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phutana, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(372, 372, 372))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(132, 132, 132)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(atta, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(besan, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idly, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maida, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jaggery, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dalda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(match, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bisc, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eggs, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(papad, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(potato, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boost, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(haldi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chilli, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(374, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1181, Short.MAX_VALUE)
                .addComponent(dalchini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jeera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(phutana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(atta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel54)
                        .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel56)
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel57)
                        .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel58)
                        .addComponent(besan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(maida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel61)
                        .addComponent(jaggery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dalda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel78))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel63)
                        .addComponent(match, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel64)
                        .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel79))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eggs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel80))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel67)
                        .addComponent(papad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(potato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel69)
                        .addComponent(boost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel70)
                        .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel71)
                        .addComponent(haldi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel72)
                        .addComponent(chilli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel83))
                    .addGap(35, 35, 35)
                    .addComponent(jLabel74)
                    .addGap(40, 40, 40)
                    .addComponent(jLabel82)
                    .addGap(38, 38, 38)
                    .addComponent(jLabel76)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        monthlybill.setText("SEARCH MONTHLY BILL");
        monthlybill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlybillActionPerformed(evt);
            }
        });

        jLabel5.setText("TOTAL BILL");

        bill.setEditable(false);
        bill.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        calc.setText("CALCULATE BILL");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(monthlybill)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(calc)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(monthlybill)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(72, 72, 72)
                .addComponent(calc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   try{
            Class.forName("java.sql.DriverManager");
            Connection  con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mess", "root","password");
            Statement menu2 =(Statement) con.createStatement();
         int Rice1=0,Dal1=0,Atta1=0,Oil1=0,Sugar1=0,Tea1=0,Salt1=0,Besan1=0,Idlyrawa1=0,Maida1=0,Jaggery1=0,Dalda1=0,Matchbox1=0
                 ,Mealmaker1=0,Biscuits1=0,Eggs1=0,Papad1=0,Potatoes1=0,Boost1=0,Lpg1=0,Haldipowder1=0,
                Chillipowder1=0,Groundnuts1=0,Jeera1=0,Phutan1=0,Dalchini1=0, Rice=0,Dal=0,Atta=0,Oil=0,Sugar=0,Tea=0
                 ,Salt=0,Besan=0,Idlyrawa=0,Maida=0,Jaggery=0,Dalda=0,Matchbox=0,Mealmaker=0,Biscuits=0,Eggs=0,Papad=0,Potatoes=0,Boost=0,Lpg=0
                 ,Haldipowder=0,
                Chillipowder=0,Groundnuts=0,Jeera=0,Phutan=0,Dalchini=0 ;
         //rajanvikash2022@gmail.com
         String alpesh="select * from price;";
         ResultSet alpesh1= menu2.executeQuery(alpesh);
         if(alpesh1.next())
         {
             Rice1=alpesh1.getInt("rice");
             Dal1=alpesh1.getInt("dal");
             Atta1=alpesh1.getInt("atta");
             Oil1=alpesh1.getInt("oil");
             Sugar1=alpesh1.getInt("sugar");
             Tea1=alpesh1.getInt("tea");
             Salt1=alpesh1.getInt("salt");
             Besan1=alpesh1.getInt("besan");
             Idlyrawa1=alpesh1.getInt("idlyrawa");
             Maida1=alpesh1.getInt("maida");
             Jaggery1=alpesh1.getInt("jaggery");
             Dalda1=alpesh1.getInt("dalda");
             Matchbox1=alpesh1.getInt("matchbox");
             Mealmaker1=alpesh1.getInt("mealmaker");
             Biscuits1=alpesh1.getInt("biscuits");
             Eggs1=alpesh1.getInt("eggs");
             Papad1=alpesh1.getInt("papad");
             Potatoes1=alpesh1.getInt("potatoes");
             Boost1=alpesh1.getInt("boost");
             Lpg1=alpesh1.getInt("lpg");
             Haldipowder1=alpesh1.getInt("haldipowder");
             Chillipowder1=alpesh1.getInt("chillipowder");
             Groundnuts1=alpesh1.getInt("groundnuts");
             Jeera1=alpesh1.getInt("jeera");
             Phutan1=alpesh1.getInt("phutan");
             Dalchini1=alpesh1.getInt("dalchini");
         }  
         String date ="" ;
             ResultSet  day2 =  menu2.executeQuery("select curdate();");
     
     
            if(day2.next())
             date=day2.getString("curdate()");
            
            
            String alpesh2="select * from indent where date='"+date+"'; ";
              ResultSet alpesh4=menu2.executeQuery(alpesh2);
            if (alpesh4.next())
            {
                Rice=alpesh4.getInt("rice");
             Dal=alpesh4.getInt("dal");
             Atta=alpesh4.getInt("atta");
             Oil=alpesh4.getInt("oil");
             Sugar=alpesh4.getInt("sugar");
             Tea=alpesh4.getInt("tea");
             Salt=alpesh4.getInt("salt");
             Besan=alpesh4.getInt("besan");
             Idlyrawa=alpesh4.getInt("idlyrawa");
             Maida=alpesh4.getInt("maida");
             Jaggery=alpesh4.getInt("jaggery");
             Dalda=alpesh4.getInt("dalda");
             Matchbox=alpesh4.getInt("matchbox");
             Mealmaker=alpesh4.getInt("mealmaker");
             Biscuits=alpesh4.getInt("biscuits");
             Eggs=alpesh4.getInt("eggs");
             Papad=alpesh4.getInt("papad");
             Potatoes=alpesh4.getInt("potatoes");
             Boost=alpesh4.getInt("boost");
             Lpg=alpesh4.getInt("lpg");
             Haldipowder=alpesh4.getInt("haldipowder");
             Chillipowder=alpesh4.getInt("chillipowder");
             Groundnuts=alpesh4.getInt("groundnuts");
             Jeera=alpesh4.getInt("jeera");
             Phutan=alpesh4.getInt("phutan");
             Dalchini=alpesh4.getInt("dalchini");
            }
           rice.setText("" + Rice1*Rice);
           dal.setText("" + Dal1*Dal);
           atta.setText("" + Atta1*Atta);
           oil.setText("" + Oil1*Oil);
           sugar.setText("" + Sugar1*Sugar);
           tea.setText("" + Tea1*Tea);
           salt.setText("" + Salt1*Salt);
           besan.setText("" + Besan1*Besan);
           idly.setText("" + Idlyrawa1*Idlyrawa);
           maida.setText("" + Maida1*Maida);
           jaggery.setText("" + Jaggery1*Jaggery);
           dalda.setText("" + Dalda1*Dalda);
           match.setText("" + Matchbox1*Matchbox);
           meal.setText("" + Mealmaker1*Mealmaker);
           bisc.setText("" + Biscuits1*Biscuits);
           eggs.setText("" + Eggs1*Eggs);
           papad.setText("" + Papad1*Papad);
           potato.setText("" + Potatoes1*Potatoes);
           boost.setText("" + Boost1*Boost);
           lpg.setText("" + Lpg1*Lpg);
           haldi.setText("" + Haldipowder1*Haldipowder);
           chilli.setText("" + Chillipowder1*Chillipowder);
           ground.setText("" + Groundnuts1*Groundnuts);
           jeera.setText("" + Jeera1*Jeera);
           phutana.setText("" + Phutan1*Phutan);
           dalchini.setText("" + Dalchini1*Dalchini);
           
         
         
                     
    }
                  catch(Exception e) 
        {
            
            JOptionPane.showMessageDialog(this,e.getMessage());
        }  
    }//GEN-LAST:event_formWindowOpened

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.show(false);
        new HOMESCREEN().show();
    }//GEN-LAST:event_backbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection  con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mess", "root","password");
            Statement menu2 =(Statement) con.createStatement();
            int Rice,Dal,Atta,Oil,Sugar,Tea,Salt,Besan,Idlyrawa,Maida,Jaggery,Dalda,Matchbox,Mealmaker,Biscuits,Eggs,Papad,Potatoes,Boost,Lpg,Haldipowder,
            Chillipowder,Groundnuts,Jeera,Phutan,Dalchini =0;

            Rice=Integer.parseInt(rice.getText());
            Dal=Integer.parseInt(dal.getText());
            Atta=Integer.parseInt(atta.getText());
            Oil=Integer.parseInt(oil.getText());
            Sugar=Integer.parseInt(sugar.getText());
            Tea=Integer.parseInt(tea.getText());
            Salt=Integer.parseInt(salt.getText());
            Besan=Integer.parseInt(besan.getText());
            Maida=Integer.parseInt(maida.getText());
            Jaggery=Integer.parseInt(jaggery.getText());
            Dalda=Integer.parseInt(dalda.getText());
            Matchbox=Integer.parseInt(match.getText());
            Idlyrawa=Integer.parseInt(idly.getText());
            Mealmaker=Integer.parseInt(meal.getText());
            Biscuits=Integer.parseInt(bisc.getText());
            Eggs=Integer.parseInt(eggs.getText());
            Papad=Integer.parseInt(papad.getText());
            Potatoes=Integer.parseInt(potato.getText());
            Boost=Integer.parseInt(boost.getText());
            Lpg=Integer.parseInt(lpg.getText());
            Haldipowder=Integer.parseInt(haldi.getText());
            Chillipowder=Integer.parseInt(chilli.getText());
            Groundnuts=Integer.parseInt(ground.getText());
            Jeera=Integer.parseInt(jeera.getText());
            Phutan=Integer.parseInt(phutana.getText());
            Dalchini=Integer.parseInt(dalchini.getText());
            String date ="" ;
            ResultSet  day2 =  menu2.executeQuery("select curdate();");

            if(day2.next())
            date=day2.getString("curdate()");
            String query = "insert into dailybill values ('"+date+"', "+Rice+" , "+Dal+" , "+Atta+" , "+Oil+" , "+Sugar+" , "+Tea+" , "+Salt+" , "+Besan+" , "+Idlyrawa+" , "+Maida+" , "+Jaggery+" , "+Dalda+" , "+Matchbox+" , "+Mealmaker+" , "+Biscuits+" , "+Eggs+" , "+Papad+" , "+Potatoes+" , "+Boost+" , "+Lpg+" , "+Haldipowder+" ,"+Chillipowder+" , "+Groundnuts+" , "+Jeera+" , "+Phutan+" , "+Dalchini+");";
            menu2.executeUpdate(query); JOptionPane.showMessageDialog(this,"Your Data Has Been Saved");

        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void monthlybillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlybillActionPerformed
        this.show(false);
        new monthlybill().show();
        
    }//GEN-LAST:event_monthlybillActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        int Rice,Dal,Atta,Oil,Sugar,Tea,Salt,Besan,Idlyrawa,Maida,Jaggery,Dalda,Matchbox,Mealmaker,Biscuits,Eggs,Papad,Potatoes,Boost,Lpg,Haldipowder,
        Chillipowder,Groundnuts,Jeera,Phutan,Dalchini=0;

        Rice=Integer.parseInt(rice.getText());
        Dal=Integer.parseInt(dal.getText());
        Atta=Integer.parseInt(atta.getText());
        Oil=Integer.parseInt(oil.getText());
        Sugar=Integer.parseInt(sugar.getText());
        Tea=Integer.parseInt(tea.getText());
        Salt=Integer.parseInt(salt.getText());
        Besan=Integer.parseInt(besan.getText());
        Maida=Integer.parseInt(maida.getText());
        Jaggery=Integer.parseInt(jaggery.getText());
        Dalda=Integer.parseInt(dalda.getText());
        Matchbox=Integer.parseInt(match.getText());
        Idlyrawa=Integer.parseInt(idly.getText());
        Mealmaker=Integer.parseInt(meal.getText());
        Biscuits=Integer.parseInt(bisc.getText());
        Eggs=Integer.parseInt(eggs.getText());
        Papad=Integer.parseInt(papad.getText());
        Potatoes=Integer.parseInt(potato.getText());
        Boost=Integer.parseInt(boost.getText());
        Lpg=Integer.parseInt(lpg.getText());
        Haldipowder=Integer.parseInt(haldi.getText());
        Chillipowder=Integer.parseInt(chilli.getText());
        Groundnuts=Integer.parseInt(ground.getText());
        Jeera=Integer.parseInt(jeera.getText());
        Phutan=Integer.parseInt(phutana.getText());
        Dalchini=Integer.parseInt(dalchini.getText());
        int alpesh5= Rice+Dal+Atta+Oil+Sugar+Tea+Salt+Besan+Idlyrawa+Maida+Jaggery+Dalda+Matchbox+Mealmaker+Biscuits+Eggs+Papad
        +Potatoes+Boost+Lpg+Haldipowder+Chillipowder+Groundnuts+Jeera+Phutan+Dalchini;

        bill.setText(""+ alpesh5);

    }//GEN-LAST:event_calcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atta;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField besan;
    private javax.swing.JTextField bill;
    private javax.swing.JTextField bisc;
    private javax.swing.JTextField boost;
    private javax.swing.JButton calc;
    private javax.swing.JTextField chilli;
    private javax.swing.JTextField dal;
    private javax.swing.JTextField dalchini;
    private javax.swing.JTextField dalda;
    private javax.swing.JTextField eggs;
    private javax.swing.JTextField ground;
    private javax.swing.JTextField haldi;
    private javax.swing.JTextField idly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jaggery;
    private javax.swing.JTextField jeera;
    private javax.swing.JTextField lpg;
    private javax.swing.JTextField maida;
    private javax.swing.JTextField match;
    private javax.swing.JTextField meal;
    private javax.swing.JButton monthlybill;
    private javax.swing.JTextField oil;
    private javax.swing.JTextField papad;
    private javax.swing.JTextField phutana;
    private javax.swing.JTextField potato;
    private javax.swing.JTextField rice;
    private javax.swing.JTextField salt;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField sugar;
    private javax.swing.JTextField tea;
    // End of variables declaration//GEN-END:variables
}
