
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jnv19
 */
public class consumption extends javax.swing.JFrame {

    /**
     * Creates new form consumption
     */
    public consumption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        chilli = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        ground = new javax.swing.JTextField();
        jeera = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        phutana = new javax.swing.JTextField();
        dalchini = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        oil = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        sugar = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        dal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        atta = new javax.swing.JTextField();
        tea = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        salt = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        besan = new javax.swing.JTextField();
        idly = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        maida = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jaggery = new javax.swing.JTextField();
        dalda = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        match = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        meal = new javax.swing.JTextField();
        bisc = new javax.swing.JTextField();
        eggs = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        papad = new javax.swing.JTextField();
        potato = new javax.swing.JTextField();
        boost = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        lpg = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        haldi = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        findbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel71.setText("HALDI POWDER");

        jLabel72.setText("CHILLI POWDER");

        jLabel74.setText("JEERA");

        jLabel76.setText("DALCHINI");

        jLabel77.setText("IDLY  RAWA");

        jLabel78.setText("DALDA");

        jLabel79.setText("BISCUITS");

        jLabel80.setText("EGGS");

        jLabel81.setText("POTATO");

        jLabel82.setText("PHUTANA");

        jLabel83.setText("GROUNDNUTS");

        jLabel1.setFont(new java.awt.Font("Typesource Extol S BRK", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 20, 237));
        jLabel1.setText("CONSUMPTION");

        jLabel2.setText("RICE");

        jLabel3.setText("DAL");

        jLabel54.setText("OIL");

        jLabel55.setText("SUGAR");

        jLabel56.setText("TEA");

        jLabel4.setText("ATTA");

        jLabel57.setText("SALT");

        jLabel58.setText("BESAN");

        jLabel60.setText("MAIDA");

        jLabel61.setText("JAGGERY");

        jLabel63.setText("MATCHBOX");

        jLabel64.setText("MEAL-MAKER");

        jLabel67.setText("PAPAD");

        jLabel69.setText("BOOST");

        jLabel70.setText("L.P.G.");

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        findbtn.setText("FIND");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("CONSUMOTION AMOUNT (KG)");

        savebtn.setText("SAVE TODAY'S CONSUMPTION");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(102, 102, 102)
                            .addComponent(savebtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(394, 394, 394)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jeera, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dalchini, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phutana, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(549, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(132, 132, 132)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(atta, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(besan, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idly, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maida, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jaggery, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dalda, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(match, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bisc, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eggs, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(papad, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(potato, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boost, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(haldi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chilli, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(545, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1168, Short.MAX_VALUE)
                .addComponent(jeera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(phutana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(dalchini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(savebtn)
                    .addComponent(findbtn))
                .addGap(318, 318, 318))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(atta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel54)
                        .addComponent(oil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel56)
                        .addComponent(tea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel57)
                        .addComponent(salt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel58)
                        .addComponent(besan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(maida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel61)
                        .addComponent(jaggery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dalda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel78))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel63)
                        .addComponent(match, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel64)
                        .addComponent(meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel79))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eggs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel80))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel67)
                        .addComponent(papad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(potato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel69)
                        .addComponent(boost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel70)
                        .addComponent(lpg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel71)
                        .addComponent(haldi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel72)
                        .addComponent(chilli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel83))
                    .addGap(35, 35, 35)
                    .addComponent(jLabel74)
                    .addGap(40, 40, 40)
                    .addComponent(jLabel82)
                    .addGap(40, 40, 40)
                    .addComponent(jLabel76)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
       this.show(false);
       new HOMESCREEN().show();
    }//GEN-LAST:event_backbtnActionPerformed

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
        this.show(false);
        new Search_Consumption().show();
    }//GEN-LAST:event_findbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
                                 
         try 
      {
          int Rice,Dal,Atta,Oil,Sugar,Tea,Salt,Besan,Idlyrawa,Maida,Jaggery,Dalda,Matchbox,Mealmaker,Biscuits,Eggs,Papad,Potatoes,Boost,Lpg,Haldipowder,
              Chillipowder,Groundnuts,Jeera,Phutan,Dalchini=0;
        Class.forName("java.sql.DriverManager");
        Connection  con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mess", "root","password");
        Statement menu2 =(Statement)con.createStatement();
          String date ="" ;
           ResultSet  day2 =  menu2.executeQuery("select curdate();");
if(day2.next())
   date=day2.getString("curdate()") ;
       String sd =  "select * from indent where date='"+date+"';";      
       ResultSet rs= menu2.executeQuery(sd);
       
       while(rs.next())
       {
            Rice=rs.getInt("rice");
            rice.setText(""+Rice);

            Dal=rs.getInt("dal");
            dal.setText(""+Dal);

            Atta=rs.getInt("atta");
            atta.setText(""+Atta);


            Oil=rs.getInt("oil");
            oil.setText(""+Oil);

            Sugar=rs.getInt("sugar");
            sugar.setText(""+Sugar);


            Tea=rs.getInt("tea");
            tea.setText(""+Tea);

            Salt=rs.getInt("salt");
            salt.setText(""+Salt);

            Besan=rs.getInt("besan");
            besan.setText(""+Besan);

            Idlyrawa=rs.getInt("idlyrawa");
            idly.setText(""+Idlyrawa);

            Maida=rs.getInt("maida");
            maida.setText(""+Maida);

            Jaggery=rs.getInt("jaggery");
            jaggery.setText(""+Jaggery);

            Dalda=rs.getInt("dalda");
            dalda.setText(""+Dalda);

            Matchbox=rs.getInt("matchbox");
            match.setText(""+Matchbox);

            Mealmaker=rs.getInt("mealmaker");
            meal.setText(""+Mealmaker);

            Biscuits=rs.getInt("biscuits");
            bisc.setText(""+Biscuits);

            Eggs=rs.getInt("eggs");
            eggs.setText(""+Eggs);

            Papad=rs.getInt("papad");
            papad.setText(""+Papad);

            Potatoes=rs.getInt("potatoes");
            potato.setText(""+Potatoes);

            Boost=rs.getInt("boost");
            boost.setText(""+Boost);

            Lpg=rs.getInt("lpg");
            lpg.setText(""+Lpg);

            Haldipowder=rs.getInt("haldipowder");
            haldi.setText(""+Haldipowder);

            Chillipowder=rs.getInt("chillipowder");
            chilli.setText(""+Chillipowder);

            Groundnuts=rs.getInt("groundnuts");
            ground.setText(""+Groundnuts);

            Jeera=rs.getInt("jeera");
            jeera.setText(""+Jeera);

            Phutan=rs.getInt("phutan");
            phutana.setText(""+Phutan);

            Dalchini=rs.getInt("dalchini");
            dalchini.setText(""+Dalchini);


      }
       
       
       
      }
      catch(Exception e)
       {
        JOptionPane.showMessageDialog(this,e.getMessage());
      }
               
    }//GEN-LAST:event_formWindowOpened

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try{
            Class.forName("java.sql.DriverManager");
            Connection dibas=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mess","root","password");
            Statement kush = dibas.createStatement();
            int Rice,Dal,Atta,Oil,Sugar,Tea,Salt,Besan,Idlyrawa,Maida,Jaggery,Dalda,Matchbox,Mealmaker,Biscuits,Eggs,Papad,Potatoes,Boost,Lpg,Haldipowder,
                Chillipowder,Groundnuts,Jeera,Phutan,Dalchini =0;
            
            Rice=Integer.parseInt(rice.getText());
            Dal=Integer.parseInt(dal.getText());
            Atta=Integer.parseInt(atta.getText());
            Oil=Integer.parseInt(oil.getText());
            Sugar=Integer.parseInt(sugar.getText());
            Tea=Integer.parseInt(tea.getText());
            Salt=Integer.parseInt(salt.getText());
            Besan=Integer.parseInt(besan.getText());
            Maida=Integer.parseInt(maida.getText());
            Jaggery=Integer.parseInt(jaggery.getText());
            Dalda=Integer.parseInt(dalda.getText());
            Matchbox=Integer.parseInt(match.getText());
            Idlyrawa=Integer.parseInt(idly.getText());
            Mealmaker=Integer.parseInt(meal.getText());
            Biscuits=Integer.parseInt(bisc.getText());
            Eggs=Integer.parseInt(eggs.getText());
            Papad=Integer.parseInt(papad.getText());
            Potatoes=Integer.parseInt(potato.getText());
            Boost=Integer.parseInt(boost.getText());
            Lpg=Integer.parseInt(lpg.getText());
            Haldipowder=Integer.parseInt(haldi.getText());
            Chillipowder=Integer.parseInt(chilli.getText());
            Groundnuts=Integer.parseInt(ground.getText());
            Jeera=Integer.parseInt(jeera.getText());
            Phutan=Integer.parseInt(phutana.getText());
            Dalchini=Integer.parseInt(dalchini.getText());
          String date ="" ;
           ResultSet  day2 =  kush.executeQuery("select curdate();");
           if(day2.next())
             date=day2.getString("curdate()") ;
            String query = "insert into consumption values ('"+date+"', "+Rice+" , "+Dal+" , "+Atta+" , "+Oil+" , "+Sugar+" , "+Tea+" , "+Salt+" , "+Besan+" , "+Idlyrawa+" , "+Maida+" , "+Jaggery+" , "+Dalda+" , "+Matchbox+" , "+Mealmaker+" , "+Biscuits+" , "+Eggs+" , "+Papad+" , "+Potatoes+" , "+Boost+" , "+Lpg+" , "+Haldipowder+" ,"+Chillipowder+" , "+Groundnuts+" , "+Jeera+" , "+Phutan+" , "+Dalchini+");";          
            kush.executeUpdate(query); JOptionPane.showMessageDialog(this,"Your Data Has Been Saved");

            
        String query1="update stock set rice=rice-"+Rice+";";
            kush.executeUpdate(query1);
            
         
        String query2="update price set dal=dal-"+Dal+";";
            kush.executeUpdate(query2);
            
        
        String query3="update price set atta=atta-"+Atta+";";
            kush.executeUpdate(query3);
            
         
        String query4="update price set oil=oil-"+Oil+";";
            kush.executeUpdate(query4);
            
         
        String query5="update price set sugar=sugar-"+Sugar+";";
            kush.executeUpdate(query5);
            
         
        String query6="update price set tea=tea-"+Tea+";";
            kush.executeUpdate(query6);
            
        
        String query7="update price set salt=salt-"+Salt+";";
            kush.executeUpdate(query7);
            
        
        String query8="update price set besan=besan-"+Besan+";";
            kush.executeUpdate(query8);
            
         
        String query9="update price set idlyrawa=idlyrawa-"+Idlyrawa+";";
            kush.executeUpdate(query9);
            
         
        String query10="update price set maida=maida-"+Maida+";";
            kush.executeUpdate(query10);
            
         
        String query11="update price set jaggery=jaggery-"+Jaggery+";";
            kush.executeUpdate(query11);
            
         
        String query12="update price set dalda=dalda-"+Dalda+";";
            kush.executeUpdate(query12);
            
         
        String query13="update price set matchbox=matchbox-"+Matchbox+";";
            kush.executeUpdate(query13);
            
        
        String query14="update price set mealmaker=mealmaker-"+Mealmaker+";";
            kush.executeUpdate(query14);
            
         
        String query15="update price set biscuits=biscuits-"+Biscuits+";";
            kush.executeUpdate(query15);
            
         
        String query16="update price set eggs=eggs-"+Eggs+";";
            kush.executeUpdate(query16);
            
         
        String query17="update price set papad=papad-"+Papad+";";
            kush.executeUpdate(query17);
            
         
        String query18="update price set potatoes=potatoes-"+Potatoes+";";
            kush.executeUpdate(query18);
            
         
        String query19="update price set boost=boost-"+Boost+";";
            kush.executeUpdate(query19);
            
         
        String query20="update price set lpg=lpg-"+Lpg+";";
            kush.executeUpdate(query20);
            
         
        String query21="update price set haldipowder=haldipowder-"+Haldipowder+";";
            kush.executeUpdate(query21);
            
         
        String query22="update price set chillipowder=chillipowder-"+Chillipowder+";";
            kush.executeUpdate(query22);
            
         
        String query23="update price set groundnuts=groundnuts-"+Groundnuts+";";
            kush.executeUpdate(query23);
            
         
        String query24="update price set jeera=jeera-"+Jeera+";";
            kush.executeUpdate(query24);
            
        
        String query25="update price set phutan=phutan-"+Phutan+";";
            kush.executeUpdate(query25);
            
        
        String query26="update price set dalchini=dalchini-"+Dalchini+";";
            kush.executeUpdate(query26);

        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consumption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consumption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consumption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consumption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consumption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atta;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField besan;
    private javax.swing.JTextField bisc;
    private javax.swing.JTextField boost;
    private javax.swing.JTextField chilli;
    private javax.swing.JTextField dal;
    private javax.swing.JTextField dalchini;
    private javax.swing.JTextField dalda;
    private javax.swing.JTextField eggs;
    private javax.swing.JButton findbtn;
    private javax.swing.JTextField ground;
    private javax.swing.JTextField haldi;
    private javax.swing.JTextField idly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaggery;
    private javax.swing.JTextField jeera;
    private javax.swing.JTextField lpg;
    private javax.swing.JTextField maida;
    private javax.swing.JTextField match;
    private javax.swing.JTextField meal;
    private javax.swing.JTextField oil;
    private javax.swing.JTextField papad;
    private javax.swing.JTextField phutana;
    private javax.swing.JTextField potato;
    private javax.swing.JTextField rice;
    private javax.swing.JTextField salt;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField sugar;
    private javax.swing.JTextField tea;
    // End of variables declaration//GEN-END:variables
}
